<center><h1>Course 2: Robot Kinematics</h1></center>

**NOTE:**
The variable names were assigned according to the code library documentation.

The python code (Modern robotics library)is commented and mostly self-explanatory in conjunction with the book. An example use is provided with each function.

Information on installing and using the library is available at the code website, https://github.com/NxRLab/ModernRobotics.

<b>Chapter 4 Forward Kinematics</b>

In [2]:
import modern_robotics as mr
import numpy as np

<b>4</b>.Referring back to Question 1 and 2, given $L=1$ and joint variable values $\theta = (-\pi/2, \pi/2, \pi/3, -\pi/4, 1, \pi/6)$, use the function `FKinSpace` in the given software to find the end-effector configuration $T \epsilon SE(3)$. The maximum allowable error for any number is 0.01, so give enough decimal places where necessary.

<img src="images/lesson1_exercise4_end_efector_conf.jpg" width=300 height=300 />

* <span style="color:gray"><b>M:</b></span>The home configuration of the end-effector

* <span style="color:gray"><b>Slist:</b></span>The joint screw axes in the space frame when the manipulator is at the home position. 

* <span style="color:gray"><b>thetalist:</b></span> A list of joint coordinate values.

* <span style="color:gray"><b>T:</b></span>The $T \epsilon SE(3)$ representing the end-effector frame when the joints are at the specified coordinates. $T_{sb}=T$

In [4]:
M = np.array([[1, 0, 0, 3.73205],
              [0, 1, 0, 0      ],
              [0, 0, 1, 2.73205],
              [0, 0, 0, 1      ]])

Slist = np.array([[ 0, 0, 0      , 0      , 0, 0       ],
                  [ 0, 1, 1      , 1      , 0, 0       ],
                  [ 1, 0, 0      , 0      , 0, 1       ],
                  [ 0, 0, 1      ,-0.73205, 0, 0       ],
                  [-1, 0, 0      , 0      , 0, -3.73205],
                  [ 0, 1, 2.73205, 3.73205, 1, 0       ]])

thetalist = np.array([-np.pi/2, np.pi/2, np.pi/3, -np.pi/4, 1, np.pi/6])

T = mr.FKinSpace(M,Slist,thetalist)

print(np.round_(T,4))

[[ 0.5     0.866   0.      1.    ]
 [ 0.2241 -0.1294 -0.9659 -1.8978]
 [-0.8365  0.483  -0.2588 -4.5085]
 [ 0.      0.      0.      1.    ]]


<b>5</b>.Referring back to Question 1 and 3, given $L=1$ and joint variable values $\theta = (-\pi/2, \pi/2, \pi/3, -\pi/4, 1, \pi/6)$, use the function `FKinBody` in the given software to find the end-effector configuration $T \epsilon SE(3)$. The maximum allowable error for any number is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>M:</b></span>The home configuration of the end-effector

* <span style="color:gray"><b>Blist:</b></span>The joint screw axes in the end-effector frame when the manipulator is at the home position. 

* <span style="color:gray"><b>thetalist:</b></span> A list of joint coordinate values.

* <span style="color:gray"><b>T:</b></span>The $T \epsilon SE(3)$ representing the end-effector frame when the joints are at the specified coordinates. $T_{bs}=T$

In [7]:
M = np.array([[1, 0, 0, 3.73205],
              [0, 1, 0, 0      ],
              [0, 0, 1, 2.73205],
              [0, 0, 0, 1      ]])

Blist = np.array([[0      , 0       , 0      , 0, 0, 0],
                  [0      , 1       , 1      , 1, 0, 0],
                  [1      , 0       , 0      , 0, 0, 1],
                  [0      , 2.73205 , 3.73205, 2, 0, 0],
                  [2.73205, 0       , 0      , 0, 0, 0],
                  [0      , -2.73205, -1     , 0, 1, 0]])

thetalist = np.array([-np.pi/2, np.pi/2, np.pi/3, -np.pi/4, 1, np.pi/6])

T = mr.FKinBody(M,Blist,thetalist)

print(np.round_(T,4))

[[ 0.5     0.866   0.      1.    ]
 [ 0.2241 -0.1294 -0.9659 -1.8978]
 [-0.8365  0.483  -0.2588 -4.5085]
 [ 0.      0.      0.      1.    ]]
