<center><h1>Course 1: Foundations of Robot Motion</h1></center>

**NOTE:**

The variable names were assigned according to the code library documentation.

The python code (Modern robotics library)is commented and mostly self-explanatory in conjunction with the book. An example use is provided with each function.

Information on installing and using the library is available at the code website, https://github.com/NxRLab/ModernRobotics.

<h2><b>Chapter 3 through 3.2, Rigid-Body Motions</b></h2>

In [1]:
import modern_robotics as mr
import numpy as np

<b>9</b>. Calculate the matrix exponential corresponding to the exponential coordinates of rotation $\hat{\omega}\theta = (1,2,0)^\intercal$ The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>expc3:</b></span> A 3-vector of exponential coordinates for rotation $\hat{\omega}\theta$
* <span style="color:gray"><b>so3mat:</b></span> The corresponding 3×3 skew-symmetric matrix in $so(3)$.
* <span style="color:gray"><b>R:</b></span> The $R'\epsilon SO(3)$ that is achieved by rotating about $\hat{\omega}$ by $\theta$ from an initial orientation $R = I$.



In [3]:
expc3 = np.array([1, 2, 0])  
so3mat =mr.VecToso3(expc3)
R = mr.MatrixExp3(so3mat)
print(np.round_(R,3))

[[-0.294  0.647  0.704]
 [ 0.647  0.677 -0.352]
 [-0.704  0.352 -0.617]]


<b>10</b>. Write the 3×3 skew-symmetric matrix corresponding to $\omega=(1,2,0.5)^T$. Confirm your answer using the function VecToso3 in the given software.

* <span style="color:gray"><b>omg:</b></span> A 3-vector
* <span style="color:gray"><b>so3mat:</b></span> The corresponding 3×3 skew-symmetric matrix in $so(3)$.

In [4]:
omg = np.array([1, 2, 0.5])
so3mat= mr.VecToso3(omg)
print (so3mat)

[[ 0.  -0.5  2. ]
 [ 0.5  0.  -1. ]
 [-2.   1.   0. ]]


<b>11.</b>Use the function `MatrixExp3` in the given software to calculate the rotation matrix $R\epsilon SO3$ corresponding to the matrix exponential of
$$[\hat{\omega}]\theta=\begin{bmatrix}
0 &0.5  &-1 \\ 
-0.5 &0  &2 \\ 
1 &-2  &0 
\end{bmatrix}$$

The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>R:</b></span> The $R'\epsilon SO(3)$ that is achieved by rotating about $\hat{\omega}$ by $\theta$ from an initial orientation $R = I$.


In [11]:
so3 = np.array([[0, 0.5, -1],
              [-0.5, 0, 2],
              [1, -2, 0]])
R = mr.MatrixExp3(so3)
print(np.round_(R,3))

[[ 0.605  0.796 -0.012]
 [ 0.468 -0.344  0.814]
 [ 0.644 -0.498 -0.581]]


<b>12.</b> Use the function `MatrixLog3` in the given software to calculate the matrix logarithm $[\hat{\omega}]\theta \epsilon so(3)$ of rotation matrix

$$R=\begin{bmatrix}
0 &0  &1 \\ 
-1 &0  &0 \\ 
0 &-1  &0 
\end{bmatrix}$$

The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>R:</b></span> Rotaion matrix
* <span style="color:gray"><b>so3mat:</b></span> The corresponding $so(3)$ representation of exponential coordinates.


In [12]:
R = np.array([[0, 0, 1],
              [-1, 0, 0],
              [0, -1, 0]])

so3mat = mr.MatrixLog3(R)
print(np.round_(so3mat,3))


[[ 0.     1.209  1.209]
 [-1.209  0.     1.209]
 [-1.209 -1.209  0.   ]]


<h2><b>Chapter 3.3 and 3.4, Rigid-Body Motions</b></h2>

<b>9</b>.Calculate the matrix exponential corresponding to the exponential coordinates of rigid-body motion $S\theta=(0,1,2,3,0,0)^T$. The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>V:</b></span> A 6-vector (representing a twist for example)

* <span style="color:gray"><b>se3mat:</b></span> The corresponding 4x4 se(3) matrix

* <span style="color:gray"><b>T:</b></span> The $T'  \epsilon ~SE(3)$ that is achieved by traveling along/about the screw axis $S$ a distance $\theta$ from an initial configuration $T=I$

In [6]:
V = np.array([0,1,2,3,0,0])
se3mat = mr.VecTose3(V)
T = mr.MatrixExp6(se3mat)
print(np.round_(T,4))

[[-0.6173 -0.7037  0.3518  1.0555]
 [ 0.7037 -0.2938  0.6469  1.9407]
 [-0.3518  0.6469  0.6765 -0.9704]
 [ 0.      0.      0.      1.    ]]


<b>11</b>.Use the function `TransInv` in the given software to calculate the inverse of the homogeneous transformation matrix: 
$$T= \begin{bmatrix}
0 &-1  &0  &3 \\ 
 1&0  &0  &0 \\ 
 0&0  &1  &1 \\ 
 0&0  &0  &1 
\end{bmatrix}$$

All elements of this matrix should be integers

* <span style="color:gray"><b>T:</b></span>Transformation matrix

* <span style="color:gray"><b>invT:</b></span> Inverse of T.

Uses the structure of transformation matrices to avoid taking a matrix inverse, for efficiency

In [7]:
T = np.array([[0, -1, 0, 3],
              [1, 0, 0, 0],
              [0, 0, 1, 1],
              [0, 0, 0, 1]])
invT=mr.TransInv(T)
print(invT)

[[ 0  1  0  0]
 [-1  0  0  3]
 [ 0  0  1 -1]
 [ 0  0  0  1]]


<b>12</b>.Write the $se(3)$ matrix corresponding to the twist $V=(1,0,0,0,2,3)^T$. All elements of this matrix should be integers.  Confirm your answer using the function `VecTose3` in the given software

* <span style="color:gray"><b>V:</b></span> A 6-vector (representing a twist for example)

* <span style="color:gray"><b>se3mat:</b></span> The corresponding 4x4 se(3) matrix

In [8]:
V = np.array([1, 0, 0, 0, 2, 3])

se3mat=mr.VecTose3(V)
print(se3mat)

[[ 0.  0.  0.  0.]
 [ 0.  0. -1.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  0.  0.]]


<b>13</b>.Use the function `ScrewToAxis` in the given software to calculate the normalized screw axis representation $S$ of the screw described by a unit vector $\hat{s}=(1,0,0)$ in the direction of the screw axis, located at the point $p=(0,0,2)$, with pitch $h=1$. All elements of this vector should be integers.

* <span style="color:gray"><b>q:</b></span> A point $q \epsilon R^3$ lying on the screw axis.
* <span style="color:gray"><b>s:</b></span> A unit vector $\hat{s} \epsilon R^3$ in the direction of the screw axis
* <span style="color:gray"><b>h:</b></span> The pitch $h \epsilon R$ (linear velocity divided by angular velocity) of the screw axis.
* <span style="color:gray"><b>S:</b></span> The corresponding normalized screw axis $S=(w,v)$

In [9]:
s = np.array([1, 0, 0])
q = np.array([0, 0, 2])
h = 1

S=mr.ScrewToAxis(q,s,h)
print(S)

[1 0 0 1 2 0]


<b>14</b>.Use the function `MatrixExp6` in the given software to calculate the homogeneous transformation matrix $T \epsilon SE(3)$ corresponding to the matrix exponential of 
$$[S]\theta=\begin{bmatrix}
0 &-1.5708  &0  &2.3562 \\ 
 1.5708&0  &0  &-2.3562 \\ 
0 &0  &0  &1 \\ 
0 &0  &0  &0 
\end{bmatrix}$$

All elements of this matrix should be integers.

* <span style="color:gray"><b>se3mat:</b></span> An se(3) representation of exponential coordinates for rigid-body motion,$[S\theta]$

* <span style="color:gray"><b>T:</b></span> The $T'  \epsilon ~SE(3)$ that is achieved by traveling along/about the screw axis $S$ a distance $\theta$ from an initial configuration $T=I$

In [12]:
se3mat = np.array([[0, -1.5708, 0, 2.3562],
                   [1.5708, 0, 0, -2.3562],
                   [0, 0, 0, 1],
                   [0, 0, 0, 0]])

T = mr.MatrixExp6(se3mat)
print(np.round_(T,4))

[[-0. -1.  0.  3.]
 [ 1. -0.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  1.]]


<b>15</b>.Use the function `MatrixLog6` in the given software to calculate the matrix logarithm $[S]\theta \epsilon se(3)$ of the homogeneous transformation matrix
$$T = \begin{bmatrix}
0 &-1  &0  &3 \\ 
1 &0  &0  &0 \\ 
0 &0  &1  &1 \\ 
0 &0  &0  &1 
\end{bmatrix}$$

The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>T:</b></span>Transformation matrix
* <span style="color:gray"><b>se3mat:</b></span> The correspinding $se(3)$ representation of exponential coordinates.


In [14]:
T = np.array([[0, -1, 0, 3],
              [1, 0, 0, -0],
              [0, 0, 1, 1],
              [0, 0, 0, 1]])

se3mat = mr.MatrixLog6(T)
print(np.round_(se3mat,3))

[[ 0.    -1.571  0.     2.356]
 [ 1.571  0.     0.    -2.356]
 [ 0.     0.     0.     1.   ]
 [ 0.     0.     0.     0.   ]]
