<center><h1>Course 1: Foundations of Robot Motion</h1></center>

<b>Chapter 3 through 3.2, Rigid-Body Motions (Modern Robotics by Frank C. Park and Kevin M. Lynch)</b>

In [2]:
import modern_robotics as mr
import numpy as np

<b>9</b>. Calculate the matrix exponential corresponding to the exponential coordinates of rotation $\hat{\omega}\theta = (1,2,0)^\intercal$ The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>expc3:</b></span> A 3-vector of exponential coordinates for rotation $\hat{\omega}\theta$
* <span style="color:gray"><b>so3mat:</b></span> The corresponding 3×3 skew-symmetric matrix in $so(3)$.
* <span style="color:gray"><b>R:</b></span> The $R'\epsilon SO(3)$ that is achieved by rotating about $\hat{\omega}$ by $\theta$ from an initial orientation $R = I$.



In [3]:
expc3 = np.array([1, 2, 0])  
so3mat =mr.VecToso3(expc3)
R = mr.MatrixExp3(so3mat)
print(np.round_(R,3))

[[-0.294  0.647  0.704]
 [ 0.647  0.677 -0.352]
 [-0.704  0.352 -0.617]]


<b>10</b>. Write the 3×3 skew-symmetric matrix corresponding to $\omega=(1,2,0.5)^T$. Confirm your answer using the function VecToso3 in the given software.

* <span style="color:gray"><b>omg:</b></span> A 3-vector
* <span style="color:gray"><b>so3mat:</b></span> The corresponding 3×3 skew-symmetric matrix in $so(3)$.

In [4]:
omg = np.array([1, 2, 0.5])
so3mat= mr.VecToso3(omg)
print (so3mat)

[[ 0.  -0.5  2. ]
 [ 0.5  0.  -1. ]
 [-2.   1.   0. ]]


<b>11.</b>Use the function MatrixExp3 in the given software to calculate the rotation matrix $R\epsilon SO3$ corresponding to the matrix exponential of
$$[\hat{\omega}]\theta=\begin{bmatrix}
0 &0.5  &-1 \\ 
-0.5 &0  &2 \\ 
1 &-2  &0 
\end{bmatrix}$$

The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>R:</b></span> The $R'\epsilon SO(3)$ that is achieved by rotating about $\hat{\omega}$ by $\theta$ from an initial orientation $R = I$.


In [11]:
so3 = np.array([[0, 0.5, -1],
              [-0.5, 0, 2],
              [1, -2, 0]])
R = mr.MatrixExp3(so3)
print(np.round_(R,3))

[[ 0.605  0.796 -0.012]
 [ 0.468 -0.344  0.814]
 [ 0.644 -0.498 -0.581]]


<b>12.</b> Use the function MatrixLog3 in the given software to calculate the matrix logarithm $[\hat{\omega}]\theta \epsilon so(3)$ of rotation matrix

$$R=\begin{bmatrix}
0 &0  &1 \\ 
-1 &0  &0 \\ 
0 &-1  &0 
\end{bmatrix}$$

The maximum allowable error for any matrix element is 0.01, so give enough decimal places where necessary.

* <span style="color:gray"><b>R:</b></span> Rotaion matrix
* <span style="color:gray"><b>so3mat:</b></span> The corresponding $so(3)$ representation of exponential coordinates.


In [12]:
R = np.array([[0, 0, 1],
              [-1, 0, 0],
              [0, -1, 0]])

so3mat = mr.MatrixLog3(R)
print(np.round_(so3mat,3))


[[ 0.     1.209  1.209]
 [-1.209  0.     1.209]
 [-1.209 -1.209  0.   ]]
